properties([pipelineTriggers([[$class: 'GitHubPushTrigger']])])

pipeline{
    agent any
    stages{
        stage ('Source Code'){
            steps{
                dir('code-source'){
                      git branch: 'development', credentialsId: 'treelogy-sandbox-github', url: 'https://github.com/treelogysystem/treelogy-template-lib/'
                }
            }
        }
          stage('Tests Units') {
              steps {
                  script {
                      sh 'mvn test'
                  }
              }
          }
          stage('Deploy Nexus Archetype') {
                steps {
                    nexusArtifactUploader credentialsId: 'treelogy-sandbox-nexus', groupId: 'treelogy.br', nexusUrl: 'nexus.treelogy.eco.br/repository/maven-group/', nexusVersion: 'nexus2', protocol: 'http', repository: 'maven-group', version: '0.0.1'
                }
          }
    }
}
