
pipeline{
    agent any
    stages{
          stage('Maven Tests') {
              steps {
                  script {
                      sh 'mvn test'
                  }
              }
          }
          stage('Maven Install') {
                steps {
                    script {
                        sh 'mvn install'
                    }
                }
          }
          stage('Deploy Nexus Archetype') {
                steps {
                    nexusArtifactUploader artifacts: [[artifactId: 'template-lib', classifier: '', file: 'target/template-lib-0.0.1-SNAPSHOT.jar', type: 'jar']], credentialsId: 'treelogy-sandbox-nexus', groupId: 'treelogy.br', nexusUrl: 'nexus.rancher.treelogy.eco.br', nexusVersion: 'nexus3', protocol: 'http', repository: 'treelogy-system-snapshot', version: '0.0.1-SNAPSHOT'
                }
          }
    }
}
